development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://nbwauknyjxvybb:bd6f8501f4a316fa905a032041aee023d7d876b8bdca1fedb5db0e971b74903c@ec2-23-21-76-49.compute-1.amazonaws.com:5432/da8i7bqsmqsp9j
